apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat-deployment
  labels:
    app: webgoat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webgoat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
      - name: webgoat
        image: cyberpwndevsec/webgoatjava:stage
        ports:
        - containerPort: 8070
 
---
 
apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
spec:
  selector:
    app: webgoat
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: NodePort
